### ISSUE TITLE
First integration test fails

### ISSUE THREAD

**Issue by juliandehne** [GESIS-Methods-Hub/ZIS_R_tutor#1]
- title block: "Last updated on" refers to the first publication date, and not to the latest version (date-modified in our quarto file)
related to the point above, the distinction between published and modified is gone (rather not super important for the aggregated file)
affiliations are gone (I guess that's not terribly important as long as all the authors are from GESIS)
- and the ZIS logo is gone 
- citations/bibliography don't work
- there's a different formatting of the callout blocks

**Comment by rgaiacs** [comment]
@juliandehne I believe that most of the listed issues are because of the Quarto to Markdown to HTML pipeline.

The better way to fix the issues is to do Quarto to HTML skipping the intermediate Markdown.

Why were we using Quarto to Markdown to HTML? Because a generate a clean Markdown was easier than generate a clean HTML. For example, `quarto render mwe.qmd --to markdown --output mwe.md` will convert

```
---
title: "mwe"
---

## Quarto

Quarto enables you to weave together content and executable code into a finished document. To learn more about Quarto see <https://quarto.org>.
```

into

```
---
title: mwe
toc-title: Table of contents
---

## Quarto

Quarto enables you to weave together content and executable code into a
finished document. To learn more about Quarto see <https://quarto.org>.
```

Unfortunately, the same command will convert

```
---
title: "mwe"
---

## Quarto

::: {.callout-note}
Note that there are five types of callouts.
:::

Quarto enables you to weave together content and executable code into a finished document. To learn more about Quarto see <https://quarto.org>.
```

into

```
---
title: mwe
toc-title: Table of contents
---

## Quarto

<div>

> **Note**
>
> Note that there are five types of callouts.

</div>

Quarto enables you to weave together content and executable code into a
finished document. To learn more about Quarto see <https://quarto.org>.
```

This is why you are getting a "different formatting of the callout blocks". The same principle apply for the other issues.

**Comment by juliandehne** [comment]
It looks like the citation issues are due to the minimal example pipeline.

**Comment by juliandehne** [comment]
License field is not rendered properly

**Comment by juliandehne** [comment]
Wrote a lua-filter that sets license: "CC BY-NC 4.0" throughout the project
